- name: hello
  hosts: local
  connection: local
  tasks:
   - name: Task1
     ansible.builtin.debug:
  tasks:
   - name: Task2
     ansible.builtin.debug:   
  tasks:
   - name: Task3
     ansible.builtin.debug:
  tasks:
   - name: Task4
     ansible.builtin.debug:   