- name: Vars inventory file
  hosts: local
  connection: local

  tasks:

   - name: print course info
     ansible.builtin.debug:
      msg: "I am learning course {{course }} DURATION OF {{duration }} by the expert Mr {{trainer}}"