# Test we can logon to 'webservers' and execute python with json lib.
# ansible webservers -m ansible.builtin.ping

- name: First Example from an Ansible Playbook
  hosts: server 
  tasks:  
  - name: ping the server
    ansible.builtin.ping: 



